recipe_webapp/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

recipe_webapp/recipe_crud/urls.py
from django.urls import path
from . import views

app_name = 'recipe_crud'

urlpatterns = [
    path('', views.PostListView.as_view(),name='list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name="detail"),
    path('create/',views.CreatePostView.as_view(),name='create'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
]

recipe_webapp/recipe_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('recipe/',include('recipe_crud.urls',namespace='recipe_crud')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_webapp/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

recipe_webapp/recipe_crud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    recipe_name = models.CharField(max_length=100)
    ingredients = models.TextField()
    author =  models.ForeignKey(User, on_delete=models.DO_NOTHING)
    direction = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images/")
    def __str__(self):
        return self.recipe_name

    def get_absolute_url(self):
        return reverse('recipe_crud:detail',
        kwargs={'pk':self.pk})

recipe_webapp/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

recipe_webapp/recipe_crud/forms.py
from socket import fromshare
from django import forms
from recipe_crud.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('recipe_name','ingredients','author','direction','thumbnail')

        widgets = {
            'ingredients': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
            'direction': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

recipe_webapp/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

recipe_webapp/recipe_crud/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from recipe_crud.models import Post
from recipe_crud.forms import PostForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView,
                                DetailView, CreateView,
                                UpdateView, DeleteView)
# Create your views here.

class  CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'recipe_crud/recipe_form.html'
    model = Post
    form_class = PostForm

class PostUpdateView(LoginRequiredMixin,UpdateView):
#     login_url = '/login/'
    template_name = 'recipe_crud/recipe_form.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('recipe_crud:list')
    context_object_name = 'recipes'
    template_name = 'recipe_crud/recipe_confirm_delete.html'

class IndexView(TemplateView):
    template_name = 'index.html'

class PostListView(ListView):
    context_object_name = 'recipes'
    template_name = 'recipe_crud/recipe_list.html'
    model = Post
    ordering = ['recipe_name']
    # paginate_by = 2


class PostDetailView(DetailView):
    context_object_name = 'recipes_detail'
    model = Post
    template_name = 'recipe_crud/recipe_detail.html'

recipe_webapp/recipe_webapp/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'
    
class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

recipe_webapp/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap5 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

recipe_webapp/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap5 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

recipe_webapp/recipe_crud/templates/recipe_crud/recipe_confirm_delete.html
{% extends "recipe_crud/recipe_crud_base.html" %}

{% block body_block %}

<h1>Delete {{recipes.recipe_name}}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'recipe_crud:list' %}">Cancel</a>
</form>

{% endblock %}

recipe_webapp/recipe_crud/templates/recipe_crud/recipe_crud_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipe Webapp</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

</head>
<body>

  <!-- Navigation Bar #TO BE DESIGNED -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
        Recipe
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'recipe_crud:list' %}" class="nav-link" href="#">Recipes</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" href="#">Groups</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" href="#">Create Group</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:logout' %}" class="nav-link" href="#">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="#" class="nav-link" href="#">Post</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="nav-link" href="#">Sign Up</a>
            </li> 
            <li class="nav-item">
              <a href="{% url 'accounts:login' %}" class="nav-link" href="#">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>

    </div>
  </nav>




  <div class="container mycontent">

  {% block body_block %}

  {% endblock %}
  
  </div>


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</body>
</html>

recipe_webapp/recipe_crud/templates/recipe_crud/recipe_detail.html
{%  extends "recipe_crud/recipe_crud_base.html" %}

{% block body_block %}
<div class="container">
    <h1>Welcome to recipe detail page</h1>
    <h2>Details:</h2>
    <p>Recipe Name: {{recipes_detail.recipe_name}}</p>
    <p>Author: {{recipes_detail.author}}</p>
    <p>Ingredients: {{recipes_detail.ingredients|safe|linebreaksbr}}</p>
    <p>Directions: {{recipes_detail.direction|safe|linebreaksbr}}</p>
    {% if recipes_detail.thumbnail %}
    <p><img src="{{ recipes_detail.thumbnail.url}}"></p>
    {% endif %}
</div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'recipe_crud:update' pk=recipes_detail.pk %}">
        Update
    </a>
    <a class='btn btn-warning' href="{% url 'recipe_crud:delete' pk=recipes_detail.pk %}">
        Delete
    </a></p>
    
</div>

{% endblock %}

recipe_webapp/recipe_crud/templates/recipe_crud/recipe_form.html
{%  extends "recipe_crud/recipe_crud_base.html" %}

{% load bootstrap5 %}

{% block body_block %}

<div class="container">
    <h1>
        {% if not form.instance.pk %}
        Create Recipe
        {% else %}
        Update Recipe
        {% endif %}
    </h1>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}

    </form>

</div>

{% endblock %}

recipe_webapp/recipe_crud/templates/recipe_crud/recipe_list.html
{%  extends "recipe_crud/recipe_crud_base.html" %}

{% block body_block %}

<h1>List of Recipes</h1>
<a class='btn btn-primary' href="{% url 'recipe_crud:create' %}">Create</a>
<ol>
    {% for recipe in recipes %}
    <h2><li>
        <a href="{{recipe.id}}">
        {{recipe.recipe_name}}
        </a>
    </li></h2>
    {% endfor %}
</ol>

{% endblock %}

recipe_webapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipe Webapp</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

</head>
<body>

  <!-- Navigation Bar #TO BE DESIGNED -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
        Recipe
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'recipe_crud:list' %}" class="nav-link" href="#">Recipes</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:logout' %}" class="nav-link" href="#">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="nav-link" href="#">Sign Up</a>
            </li> 
            <li class="nav-item">
              <a href="{% url 'accounts:login' %}" class="nav-link" href="#">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>

    </div>
  </nav>




  <div class="container mycontent">

  {% if user.is_authenticated %}

  {% else %}
  <p>Please Login to the website to access data</p>
  {% endif %}

  {% block content %}

  {% endblock %}
  
  </div>


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</body>
</html>

recipe_webapp/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>WELCOME TO RECIPE WEBAPP</h1>
{% endblock %}

recipe_webapp/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

recipe_webapp/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}